### ISSUE TITLE
Create a project on Azure

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt-release-testbot#8]
The testbot relies on Azure Pipelines CI service to test GMT packages from different sources. It seems I don't have the permission to create a project under GenericMappingTools account (https://dev.azure.com/GenericMappingTools/).

@leouieda Could you please help create a project on Azure?

**Comment by leouieda** [comment]
@seisman done! https://dev.azure.com/GenericMappingTools/gmt-release-test-bot/_build/results?buildId=4137

I tried to change your access level. See if you can create projects now. Azure is so complicated and corporate. If only Travis was still a better service...

**Comment by seisman** [comment]
Great! Thanks.

I still can't create a project. I'm also not a member of the "gmt-release-test-bot" project, and can't make changes to this project.

**Comment by leouieda** [comment]
OK, I added you to the project as an admin. But it seems that the organization as a whole can only have one owner. I'm not sure what that means, though.

**Comment by seisman** [comment]
OK, thanks.
